version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: ["./wait-for-postgres.sh", "db", "rake db:create", "rake db:migrate", "bin/rails s -b '0.0.0.0'"]
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
    depends_on:
      - db